#!/bin/zsh

TEXLIVE=/usr/local/texlive/bin/x86_64-linux/

rm -f thesis.{aux,bbl,bcf,blg,glo,idx,ilg,ind,loa,log,out,run.xml,toc,xdy}
rm -f thesis-blx.bib
rm -f thesis.glsdefs

$TEXLIVE"pdflatex" thesis &&
  $TEXLIVE"biber" thesis &&
  $TEXLIVE"pdflatex" thesis &&
  $TEXLIVE"makeindex" thesis.idx &&
  $TEXLIVE"pdflatex" thesis
